version: 1.0.{build}
configuration:
- Release
- Debug
platform: Any CPU
os: Visual Studio 2015
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: false
  include_nuget_references: true
  verbosity: minimal
after_build:
- 7z a RServeCLI2.zip %APPVEYOR_BUILD_FOLDER%\RServeCLI2\bin\%CONFIGURATION%\*.* -r
- 7z a RServeCLI2.Example.zip %APPVEYOR_BUILD_FOLDER%\RServeCLI2.Example\bin\%CONFIGURATION%\*.* -r
- 7z a RServeCLI2.Test.zip %APPVEYOR_BUILD_FOLDER%\RServeCLI2.Test\bin\%CONFIGURATION%\*.* -r
artifacts:
- path: RServeCLI2.zip
- path: RServeCLI2.Example.zip
- path: RServeCLI2.Test.zip
deploy:
  provider: NuGet
  api_key:
    secure: aUaOAaFmJX9VJGINuxJ86ljfbXzi6I748PR0zL8VdZElrdh7C0sbPoFRKl8eciDY
  artifact: /.*\.nupkg/